[package]
name = "avl_tree_map"
version = "0.1.0"
edition = "2021"
description = "An implementation of AVL tree with a BTreeMap-like API"

[dependencies]

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
